spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.21.23.199:8080/realms/Spring-login
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: login-app
      principle-attribute: preferred_username
      
server:
  port: 9090
